= Tests pour les auteurs de politiques :revdate:2025 03.06.2017 :page-revdate: {revdate} :description: une Introduction au Test des politiques Kubewarden pour les auteurs de politiques. :doc-persona: ["kubewarden-Policy-Developer"] :doc-topic: ["Testing-policies", "Policy-Writers"] :doc-type:\["Tutoriel"] :keywords: ["kubewarden", "Policy Testing", "Policy Author", "rouille", „Go“, „assembyscript“, „Development Environment“] :sidebar_label:Autorinnen und Autoren :current-version:{page-origin-Branch}

Les politiques Kubewarden sont des programmes réguliers compilés sous forme de WebAssembly (Wasm). Comme pour tout type de Program, une bonne Couverture de Test EST Importante.

Les auteurs de stratégies peuvent utiliser leurs environnements de développement préférés. Vous pouvez utiliser des outils familiers et des Frameworks de Test pour vérifier le développement.

CES règles Kubewarden sont des exemples écrits dans xref:Tutorials/writing-policies/Rust/01-intro-Rust.adoc[Rust] et xref:Tutorials/writing-policies/go/01-intro-go.adoc[go]&nbsp;:

* https://github.com/kubewarden/psp-apparmor\[psp-apparmor]
* https://github.com/kubewarden/ingress-policy\[ingress-policy]

ILS Disposent de Suites de Tests utilisant des Tests Standard pour leurs Environnements de développement.

Les politiques nutzt des Actions GitHub pour leurs Pipelines ci.

== Tests de bout en bout

Vous pouvez également écrire des Tests qui s'exécutent sur le binaire Wasm Contenant votre stratégie. Pour ce faire sans avoir à déployer un Cluster Kubernetes, vous pouvez utiliser ces outils&nbsp;:

* https://github.com/bats-core/bats-core[bats]: EST&nbsp;: EST d'écrire des Testes et d'Automatiser leur exécution.
* https://github.com/kubewarden/kwctl\[`kwctl`]&nbsp;: Outil CLI par défaut de Kubewarden qui vous aide avec les opérations liées aux stratégies&nbsp;: extraire, Inspecter, annoter, pousser, et courez.

Pour utiliser`kwctl run`, vous avez besoin des éléments suivants&nbsp;:

. Référence du fichier binaire Wasm de la stratégie à exécuter. La stratégie Kubewarden peut être chargée à partir de&nbsp;: ** Le système de fichiers local (`file://`) ** un serveur HTTP(s) (`https://` ** un registre OCI (`registry://`). . Prüfgerät Objet de demande d'Accession à. Vue le donnez via l'`--request-path`Argument, ou on `stdin` en définissant `--request-path` sur `-`. . Les paramètres de stratégie pour l'exécution en tant que JSON en ligne via `--settings-json` drapeau. Ou un fichier JSON, ou YAML, chargé à partir du système de fichiers via `--settings-path`.

Après le Test `kwctl`, imprime l'`ValidationResponse`objet sur la sortie Standard.

Voici comment vous utilisez `kwctl` pour Tester le binaire Wasm du https://github.com/kubewarden/ingress-policy\[`ingress-policy`] mentionné précédemment&nbsp;:

\[Subs=„+attributes“,Console]
---

$ curl https://raw.githubusercontent.com/kubewarden/ingress-policy/v0.1.8/test_data/ingress-wildcard.json 2> /dev/null |  
kwctl Run  
\--settings-JSON '{"allowPorts"&nbsp;: [80], «&nbsp;denyPorts&nbsp;»&nbsp;: [3000]}'  
\--Request-path -  
Register&nbsp;://ghcr.io/kubewarden/policies/ingress:v0.1.8 | jq
---

Vous pouvez télécharger les binaires pré-construits de `kwctl` https://github.com/kubewarden/kwctl/releases[here].

De utilisant `bats` vous pouvez écrire un Test qui exécute cette commande et recherche les sorties attendues&nbsp;:

.A Test chauves-souris

\[%komprimierbar]
===

\[,bash]
---

@test "Tout va bien" { Run kwctl Run  
\--Request-path Test_Data/ingress-wildcard.JSON  
\--settings-JSON '{"allowPorts"&nbsp;: [80], «&nbsp;denyPorts&nbsp;»&nbsp;: [3000]}'  
Ingress-Policy.WASM

# ceci imprime la sortie lorsque l'une des vérifications ci-dessous échoue

Echo «&nbsp;Ausgabe = ${output}&nbsp;»

# Validierung des paramètres réussie

[\[ "$output" == *"gültig&nbsp;: wahr"* ]]

# Demande accept tée

[\[ "$output" == *"erlaubt&nbsp;: wahr"* ]]

}
---

\======

Vous pouvez placer le Code dans un fichier, `e2e.bats`, par example, puis invoquer `bats` par&nbsp;:

\[Subs=„+attributes“,Console]
---

$ Bats e2e.Bats ✓ tout EST bon

1 Prüfung, 0 Prüfungen
---

xref:Tutorials/writing-policies/GO/05-e2e-Tests.adoc[cette] Section de la documentation contient plus d'informations sur l'écriture de Tests de bout en bout de vos stratégies.