= test per gli operatori cluster :revdate:2025-05-09 :page-revdate: {revdate} :description: un'introduzione al test delle politiche Kubewarden per gli operatori cluster. :doc-persona: ["kubewarden-policy-Developer"] :doc-topic: ["testing-policies", "cluster-operators"] :doc-type: ["tutorial"] :keywords: ["kubewarden", "kubernetes", "cluster operators", "testing"] :sidebar_label: Cluster Operators :current-version: {page-origin-Branch}

In qualità di operatore cluster Kubernetes, è necessario eseguire test per i criteri Kubewarden che si desidera utilizzare.

Avrai domande come:

* Quali sono le impostazioni corrette dei criteri per ottenere il risultato di convalida/mutazione necessario?
* Come posso essere sicuro che tutto funzioni come previsto quando: ** aggiornare il criterio a una versione più recente? ** Aggiungere/cambiare risorse Kubernetes? ** modificare i parametri di configurazione della policy? ** e così via?

Kubewarden ha un'utilità, https://github.com/kubewarden/kwctl\[`kwctl`], che permette di testare le politiche al di fuori di Kubernetes.

Per utilizzarlo`kwctl`, è necessario richiamarlo con i seguenti input:

. Un URI del file binario WebAssembly del criterio da eseguire. Il criterio Kubewarden può essere caricato da: ** Filesystem locale `file://`** un server HTTP(S) `https://`** un registro OCI `registry://`. . Oggetto richiesta di ammissione da testare. Lo dai con la `--request-path` discussione. Utilizzare `stdin`impostando `--request-path` su `-`. . Le impostazioni dei criteri per il runtime come JSON inline tramite `--settings-json` flag. O un file JSON, o YAML, caricato dal file system tramite `--settings-path`.

Al termine del test `kwctl`, stampa l'`ValidationResponse`oggetto sull'output standard.

È possibile scaricare i file binari predefiniti di `kwctl` https://github.com/kubewarden/kwctl/releases[here].

== Un esempio di test

In questa sezione viene descritto come testare il criterio https://github.com/kubewarden/psp-apparmor[psp-apparmor] con configurazioni diverse e oggetti di richiesta di convalida.

==== Crea `AdmissionReview` richieste

È necessario creare file che contengono gli `AdmissionReview` oggetti per testare il criterio.

È possibile creare un file con il nome `pod-req-no-specific-apparmor-profile.json`seguente:

.pod-req-no-specific-apparmor-profile.json  
\[%collapsible]
===

\[subs="+attributi",json]
---

{  
"uid": "1299d386-525b-4032-98ae-1949f69f9cfc",  
"tipo": {  
"tipo": "Pod",  
"versione": "v1"  
},  
"oggetto": {  
"metadati": {  
"nome": "no-apparmor"  
},  
"spec": {  
"contenitori": \[  
{  
"immagine": "nginx",  
"nome": "nginx"  
  
  
 } ] } }  
,  
"operazione": "CREA",  
"richiedente Kind": {"versione": "v1", "tipo": "Pod"},  
"userinfo": {  
"nome utente": "alice",  
"uid": "alice-uid",  
"gruppi": ["sistema:autenticato"]  
} }  

---

\======

Questa richiesta tenta di creare un Pod che non specifica alcun profilo AppArmor da utilizzare. Questo perché non ha un `annotation` con la `container.apparmor.security.beta.kubernetes.io/<container-name>` chiave.

È possibile creare un file con il nome `pod-req-apparmor-unconfined.json`seguente:

.pod-req-apparmor-unconfined.json  
\[%comprimibile]
===

\[subs="+attributi",json]
---

{  
"uid": "1299d386-525b-4032-98ae-1949f69f9cfc",  
"tipo": {  
"tipo": "Pod",  
"versione": "v1"  
},  
"oggetto": {  
"metadati": {  
"nome": "pod con privilegi",  
"annotazioni": {  
"container.apparmor.security.beta.kubernetes.io/nginx": "non confinato"  
  
 } },  
"spec": {  
"contenitori": \[  
{  
"immagine": "nginx",  
"nome": "nginx"  
  
  
 } ] } }  
,  
"operazione": "CREA",  
"richiedente Kind": {"versione": "v1", "tipo": "Pod"},  
"userinfo": {  
"nome utente": "alice",  
"uid": "alice-uid",  
"gruppi": ["sistema:autenticato"]  
} }  

---

\======

Questa richiesta tenta di creare un Pod con un contenitore denominato `nginx` in esecuzione con il `unconfined`profilo AppArmor. Questo è solo a scopo di esercitazione. L'esecuzione in `unconfined` modalità non è una pratica di sicurezza valida.

Ora è possibile creare un file con il nome `pod-req-apparmor-custom.json`seguente:

.pod-req-apparmor-custom.json  
\[%comprimibile]
===

\[subs="+attributi",json]
---

{  
"uid": "1299d386-525b-4032-98ae-1949f69f9cfc",  
"tipo": {  
"tipo": "Pod",  
"versione": "v1"  
},  
"oggetto": {  
"metadati": {  
"nome": "pod con privilegi",  
"annotazioni": {  
"container.apparmor.security.beta.kubernetes.io/nginx": "localhost/nginx-custom"  
  
 } },  
"spec": {  
"contenitori": \[  
{  
"immagine": "nginx",  
"nome": "nginx"  
  
  
 } ] } }  
,  
"operazione": "CREA",  
"richiedente Kind": {"versione": "v1", "tipo": "Pod"},  
"userinfo": {  
"nome utente": "alice",  
"uid": "alice-uid",  
"gruppi": ["sistema:autenticato"]  
} }  

---

\======

\[NOTA]
===

Sono tutti oggetti semplificati`AdmissionReview`.  
Vengono utilizzati solo i campi rilevanti per il test della politica.
===

=== testare il criterio

Ora è possibile utilizzare `kwctl` per testare la creazione di un Pod che non specifica un profilo AppArmor:

\[subs="+attributi",console]
---

$ kwctl run  
\--request-path pod-req-no-specific-apparmor-profile.json  
registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4  
| jq
---

Il criterio accetta la richiesta e produce output come:

\[subs="+attributi",console]
---

{  
"uid": "1299d386-525b-4032-98ae-1949f69f9cfc",  
"consentito": vero  
}
---

Il criterio rifiuta la creazione di un Pod con un `unconfined`profilo AppArmor:

\[subs="+attributi",console]
---

$ kwctl run  
\--request-path pod-req-apparmor-unconfined.json  
registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4  
| jq  
{  
"uid": "1299d386-525b-4032-98ae-1949f69f9cfc",  
"consentito": falso,  
"stato": {  
"messaggio": "Questi profili AppArmor non sono consentiti: ["non confinato"]"  
} }  

---

In entrambe le occasioni hai eseguito la politica *senza* fornire alcun tipo di impostazione. Come afferma la documentazione https://github.com/kubewarden/psp-apparmor#configuration[policy's], ciò impedisce l'uso di profili non predefiniti.

Anche il Pod che utilizza un profilo personalizzato `nginx`viene rifiutato dal criterio:

\[subs="+attributi",console]
---

$ kwctl run  
\--request-path pod-req-apparmor-custom.json  
registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4  
| jq  
{  
"uid": "1299d386-525b-4032-98ae-1949f69f9cfc",  
"consentito": falso,  
"stato": {  
"messaggio": "Questi profili AppArmor non sono consentiti: ["localhost/nginx-custom"]"  
} }  

---

È possibile modificare il comportamento predefinito, consentendo l'utilizzo dei profili AppArmor selezionati:

\[subs="+attributi",console]
---

$ kwctl run  
\--request-path pod-req-apparmor-custom.json  
\--settings-json '{"allowed_profiles": ["runtime/default", "localhost/nginx-custom"]}'  
registro di sistema://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4  
| jq
---

A questo punto, la richiesta riesce:

\[subs="+attributi",console]
---

{  
"uid": "1299d386-525b-4032-98ae-1949f69f9cfc",  
"consentito": vero  
}
---

== automazione

È possibile automatizzare tutti questi passaggi utilizzando https://github.com/bats-core/bats-core[bats].

È possibile scrivere una serie di test e integrarne l'esecuzione all'interno delle pipeline ci e CD esistenti.

I comandi possono essere "inseriti" in un `bats` test:

.A Batstest  
\[%Collapsible]
===

\[,bash]
---

@test "tutto è buono" { run kwctl run  
\--request-path pod-req-no-specific-apparmor-profile.json  
registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4

# questa operazione stampa l'output quando uno dei controlli seguenti non riesce

eco "output = ${output}"

# richiesta accettata

\[ $(expr "$output" : '.*"consentito":vero.*') -ne 0 ] }

@test "rifiuta" { run kwctl run  
\--request-path pod-req-apparmor-custom.json  
registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.4

# questa operazione stampa l'output quando uno dei controlli seguenti non riesce

eco "output = ${output}"

# richiesta rifiutata

\[ $(expr "$output" : '.*"consentito":falso.*') -ne 0 ]  
}
---

\======

Se il `bats` codice è nel file `e2e.bats`, è possibile eseguire il test come segue:

\[subs="+attributi",console]
---

$ bats e2e.bats ✓ tutto è buono ✓ rifiutare

2 test, 0 errori
---

Xref:tutorials/writing-policies/go/05-e2e-Tests.adoc[this] sezione contiene ulteriori informazioni sulla scrittura di test end-to-end per le policy.