= Données de test des politiques :revdate:2025-05-09 :page-revdate: {revdate} :description: un tutoriel sur le test des politiques dans Kubewarden. :doc-persona: ["kubewarden-operator", "kubewarden-policy-developer"] :doc-topic: ["testing-policies", "introduzione"] :doc-type: ["tutoriel"] :keywords: ["kubewarden", "persone", "autore della politica", «&nbsp;cluster operator&nbsp;»] :sidebar_label:test de règle :current-version:{page-origin-branch}

== personas de test de règles

Cette section traite du test des politiques Kubewarden. Il y a deux personas intéressés par les politiques de test&nbsp;:

* *Développeur de politiques*&nbsp;: vous écrivez une politique Kubewarden et vous voulez vous assurer que votre code se comporte comme vous l'attendez.
* *Opérateur de cluster*&nbsp;: vous avez trouvé une stratégie Kubewarden et vous souhaitez tester et ajuster les paramètres de stratégie avant de la déployer. Vous souhaitez Continuer à tester ces paramètres dans vos Pipeline ci/CD, ainsi que dans d'autres tâches amministrazioni.

Les sections suivantes de la documentation montrent comment ces personas peuvent tester les stratégies Kubewarden.