= Policy Testing Data :revdate: 2025 09.05.2009 :page-revdate: {revdate} :description: Ein Tutorial zum Testen von Richtlinien in Kubewarden. :doc-persona: ["kubewarden-Operator", "kubewarden-Policy-Developer"] :doc-topic: ["Testing-Policies", "Einführung"] :doc-type:\["Tutorial"]  \[":keywords:kubewarden", "Personen", "Policy Author", „Cluster Operator“] :sidebar_label: Policy-Test :current-version: {page-origin-Branch}

== Personas zum Testen von Richtlinien

In diesem Abschnitt wird das Thema Testen von Kubewarden Richtlinien behandelt. Es gibt zwei Personen, die sich für das Testen von Richtlinien interessieren:

* *Richtlinienentwickler*: Sie schreiben eine Kubewarden-Richtlinie und möchten sicherstellen, dass Ihr Code sich wie erwartet verhält.
* *Cluster Operator*: Sie haben eine Kubewarden Policy gefunden und möchten die Richtlinieneinstellungen vor der Bereitstellung testen und optimieren. Sie möchten diese Einstellungen weiterhin in Ihren CI/CD-Pipelines und anderen administrativen Aufgaben testen.

Die nächsten Abschnitte der Dokumentation zeigen, wie diese Personas Kubewarden Richtlinien testen können.